[package]
name = "bartos"
version = "0.1.0"
edition = "2024"

[features]
unstable = [ "libbarto/unstable" ]

[dependencies]
actix-web = { workspace = true, features = ["rustls-0_23"] }
actix-ws = "0.3.0"
anyhow = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
futures-util = { workspace = true }
getset = { workspace = true }
libbarto = { path = "../libbarto" }
rustls = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber-init = { workspace = true }

[build-dependencies]
rustversion = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
