on:
  workflow_dispatch:
  # Trigger the workflow on push to master or any pull request
  # Ignore all tags
  push:
    branches:
      - master
    tags-ignore: 
      - "*"
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "22 3 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

name: 💣 Audit 💣

jobs:
  audit-check:
    runs-on: ubuntu-latest
    name: 💣 Audit 💣
    steps:
      - name: ✅ Checkout ✅
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: 💣 Audit 💣
        id: audit
        uses: rustyhorde/audit-check@d4c2608684a8438b87769d0f0acdd802652a5ddb # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deny: 'warnings'
          create_issue: 'true'