on:
  workflow_dispatch:
  # Trigger the workflow on push to master or any pull request
  # Ignore all tags
  push:
    branches:
      - master
    tags-ignore: 
      - "*"
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "22 3 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

name: 💣 Audit 💣

jobs:
  audit-check:
    runs-on: ubuntu-latest
    name: 💣 Audit 💣
    steps:
      - name: ✅ Checkout ✅
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 💣 Audit 💣
        id: audit
        uses: rustyhorde/audit-check@7e8e8dfe2895df67935c2572a323b28efbb9d137 # main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deny: 'warnings'
          create_issue: 'true'